NOAA-OWP/ngen-cal

python/ngen_cal/__init__.py, python/ngen_cal/calibratable.py, python/ngen_cal/calibration.py, python/ngen_cal/calibration_cathment.py, python/ngen_cal/configuration.py, python/ngen_cal/meta.py, python/ngen_cal/objectives.py, python/ngen_cal/search.py, python/ngen_cal/test/data/example_realization_config.json, python/ngen_cal/test/test_configuration.py, python/ngen_cal/test/test_objectives.py, python/ngen_cal/test/test_search.py, requirements.txt
This work in progress attempts to define a simple calibratable interface that is useable by the search algorithm (DDS).  A `hypy.Catchment` subclass implements this interface and makes the connection of the abstract data to an operable form.
Related to noaa-owp/hypy#6
Closes #1 
- `calibrateable.py`
- `calibration_catchment.py
- `search.py`
- removed dds loop from `calibraiton.py` into its own function in `search.py`
1. test module for `search.py` in place, others need created to finish this PR.
- TEST COVERAGE!
=> Calibratable Implementation

python/ngen_conf/src/ngen/config/configurations.py, python/ngen_conf/tests/conftest.py, python/ngen_conf/tests/test_cfe.py, python/ngen_conf/tests/test_lstm.py, python/ngen_conf/tests/test_realization.py, python/ngen_conf/tests/test_topmod.py
Closes #22.
- NetCDF forcing provider type
-
- Forcing type of a realization is no longer const
1. All unit tests using Forcing fixture were paramterized and now run with both netcdf and csv provided types
=> Add netcdf provider

python/ngen_conf/setup.cfg, python/ngen_conf/src/ngen/config/path_pair/__init__.py, python/ngen_conf/src/ngen/config/path_pair/_abc_mixins.py, python/ngen_conf/src/ngen/config/path_pair/_mixins.py, python/ngen_conf/src/ngen/config/path_pair/_utils.py, python/ngen_conf/src/ngen/config/path_pair/common.py, python/ngen_conf/src/ngen/config/path_pair/path_pair.py, python/ngen_conf/src/ngen/config/path_pair/protocol.py, python/ngen_conf/src/ngen/config/path_pair/typing.py, python/ngen_conf/tests/test_path_pair.py
Add new `PathPair` and `PathPairCollection` types that encapsulate a `pathlib.Path` and some inner `T` or collection of `T`'s. Beyond encapsulation, these types also provide APIs for flexibly writing, reading, serializing, deserializing to and from the inner `T` / `T`'s.
This functionality is desirable, among other use cases, when using `pydantic` and want to represent a field that de/serializes as a `pathlib.Path` but holds onto an inner deserialized `T` (this could be another pydantic model for example).
```python
from pydantic import BaseModel, validator
from ngen.config.path_pair import PathPair
from ngen.config.path_pair.common import pydantic_serializer, pydantic_deserializer
import tempfile
from typing import Union
class Inner(BaseModel):
foo: int
class Outer(BaseModel):
path: …
```
=> Add PathPair and PathPairCollection types

.github/workflows/ngen-cal.yaml, .github/workflows/ngen-conf.yml, .github/workflows/ngen-init-config.yml
`pip freeze` dependency versions in gh actions. This is mainly for debugging purposes in the case that test runners start failing.
=> List dependency versions in gh actions

python/ngen_cal/setup.cfg
In reading through [`pandas` 2.0 change log](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v2.0.0.html#backwards-incompatible-api-changes) and reviewing the existing code, we don't appear to use any features that were broken in 2.0. @hellkite500, can you have another look to audit that codebase and double check me? Luckily, there arent too many places where pandas is being used. 
- Bump ngen.cal pandas dependency to pandas >=1.1.2
=> Bump ngen.cal pandas dependency to pandas >=1.1.2

python/ngen_conf/src/ngen/config/init_config/value_unit_pair.py, python/ngen_conf/tests/test_value_unit_pair.py
Add `ValueUnitPair` and `ListUnitPair` classes. The former captures the concept of a value and a unit (i.e. `42[meters]`) while the latter is an extension of the concept but for a list of values.
Why do we need this? BMI modules: soil freeze thaw, soil moisture profile, lgar, and CFE all use this format in their configuration files. These classes provide a way for capturing the expressed concept as pydantic models. This will enable adding the aforementioned modules to `ngen.config`.
- There are a few PRs that I am in the process of staging that will result in a `ngen.config` version bump, but this alone does not constitute a version bump.
=> feat: `value_unit_pair` module

python/ngen_conf/src/ngen/config/model_vars.py, python/ngen_conf/tests/test_model_vars.py
This PR introduces the `ngen.config.model_vars` module (open to changing the name, please make suggestions). The module introduces functions and abstractions for representing and resolving NextGen BMI module input and output variables. For example, this feature set enables representing a set of BMI modules and determining which outputs map to which inputs. Likewise, it enables validating that a set of modules' output variables are valid under the NextGen frameworks invariants.
See tests for example usage.
- `ngen.config.model_vars` functions and abstractions for representing and resolving NextGen BMI module input and output variables. Functions of note are:
- `resolve_model_inputs`: Returns the input mappings and missing inputs for a single model.
- `resolve_inputs_mapping`: Returns the …
=> Represent and resolve NextGen BMI module input and output variables

python/ngen_cal/src/ngen/cal/ngen.py
Support geopackage hydrofabric inputs.  This maintains compatibility with the old geo-json input for now, but will print a deprecation warning when trying to use them.
Note that all hydrofabric keys are now optional in the config, but either hydrofabric or the the 3 geoson need to be provided for validation to succeed.  If both hydrofabric and geojson are provided, the geojson will be silently ignored (other than the deprecation warning...) and the hydrofabric input key will be used to initialize the model.
=> Gpkg support

python/ngen_cal/src/ngen/cal/__init__.py, python/ngen_cal/src/ngen/cal/_hookspec.py, python/ngen_cal/src/ngen/cal/calibratable.py, python/ngen_cal/src/ngen/cal/calibration_set.py, python/ngen_cal/src/ngen/cal/model.py, python/ngen_cal/src/ngen/cal/ngen.py, python/ngen_cal/src/ngen/cal/ngen_hooks/ngen_output.py, python/ngen_cal/src/ngen/cal/search.py, python/ngen_cal/tests/test_model.py, python/ngen_cal/tests/test_plugin_system.py
At some point t-route stopped supporting `flowveldepth` output in hdf5 form.  However, it will still output the `flowveldepth` in a csv file which can be used very similarly.  This PR updates routing output to support reading the csv output instead of hdf5.
Also, when multiple runs of t-route are used, a cleanup of the `*NEXOUT.parquet` files is needed, so that was added here in the `update_config` step to ensure a clean directory for each calibration iteration.
Only works once noaa-owp/t-route#788 is applied, otherwise t-route will still throw an error when run through ngen-cal since the working directory contains other, non-troute specific, parquet files (see noaa-owp/t-route#787)
=> Update to use t-route output in csv form

python/ngen_cal/src/ngen/cal/ngen.py
Quick fix. [`hypy #35`](https://github.com/NOAA-OWP/hypy/pull/35/files#diff-92d459a30b727fa8a724dc6151a2934a8fd56081bc0fcbf00a2555110a2cfe64R97) added an `AssertionError` that is causing our tests to fail. `hypy` code is right and we should be throwing.
Fixes [failing tests](https://github.com/NOAA-OWP/ngen-cal/actions/runs/10096376935/job/28081360039)
=> fix: create and pass `hypy.Catchment` object when creating `hypy.Nexus`

python/ngen_cal/src/ngen/cal/ngen.py
Newer HF versions now use:
`flowlines` instead of `flowpaths`
`flowpath-attributes` instead of `flowpath_attributes`
`model-attributes` instead of `model_attributes`
This just adds support for that.
- Add support for hydrofabrics that use `flowlines` and `flowpath-attributes`
=> fix / feat: handle building gpkg crosswalk from `flowpath-attributes`

python/ngen_cal/src/ngen/cal/calibration_set.py
This fixes an issue uncovered after merging #141. Pre-141 we were, incorrectly, passing a `str` around when it was expected to be a `hypy.Catchment`. We were calling `str` methods on what should be and now is a `hypy.Catchment` instance. This resolves that issue.
=> fix: remapping cat -> wb. related to #141

python/ngen_cal/src/ngen/cal/ngen.py
closes #134
Add support for forcing files without patterns (e.g. `netcdf`).
=> fix: allow netcdf forcing

.github/workflows/ngen-conf.yml, .github/workflows/ngen-init-config.yml, python/ngen_conf/setup.cfg, python/ngen_init_config/setup.cfg
See [python's end-of-life schedule](https://devguide.python.org/versions/#unsupported-versions).
`python 3.7` end-of-life was 2023-06-27. `python 3.8` end-of-life is on the horizon, but there are not plans at this time to remove support.
Closes #132
- Remove support for `python 3.7`
- Remove support for `python 3.7`
=> Bump minimum supported `python>=3.8`

python/ngen_cal/src/ngen/cal/_hookspec.py, python/ngen_cal/src/ngen/cal/calibration_set.py, python/ngen_cal/src/ngen/cal/ngen.py, python/ngen_cal/src/ngen/cal/ngen_hooks/observations.py, python/ngen_cal/tests/test_plugin_system.py
`ngen_cal_model_observations` is called during each calibration iteration to provide truth / observation values in the form of a `pandas.Series`, indexed by time with a record every `simulation_interval`. The returned `pandas.Series` should be in units of cubic meters per second.
A default implementation is included in this PR the pulls data from the USGS NWIS IV data service using [`hydrotools.nwis_client`](https://github.com/NOAA-OWP/hydrotools/tree/main/python/nwis_client). This is enabled by default and does not require modifying configuration files.
Hook signature:
```python
class ModelHooks:
@hookspec(firstresult=True)
def ngen_cal_model_observations(
self,
id: str,
start_time: datetime,
end_time: datetime,
simulation_interval: pd.Timedelta,
) -> pd.Series:
"""
`id`: USGS gage …
```
=> feat: `ngen_cal_model_observations` model plugin hook and default implementation

python/ngen_cal/src/ngen/cal/__main__.py, python/ngen_cal/src/ngen/cal/_hookspec.py, python/ngen_cal/src/ngen/cal/agent.py, python/ngen_cal/src/ngen/cal/ngen.py, python/ngen_cal/tests/conftest.py, python/ngen_cal/tests/test_plugin_system.py
Add model hook: `ngen_cal_model_configure` hook that mirrors the existing `ngen_cal_configure` hook.
```python
@hookspec
def ngen_cal_model_configure(self, config: ngen.cal.model.ModelExec) -> None:
"""
Called before calibration begins.
This allow plugins to perform initial configuration.
Plugins' configuration data should be provided using the
`plugins_settings` field in the `model` section of an `ngen.cal`
configuration file.
By convention, the name of the plugin should be used as top level key in
the `plugin_settings` dictionary.
"""
```
- `ngen_cal_model_configure` model hook; Called before calibration begins. This allow plugins to perform initial configuration.
- `unwrap` method added to `ngen.cal.ngen.Ngen`. Returns the instance's `__root__` attribute.
- `Agent` now takes a `Model` …
=> feat: `ngen_cal_model_configure` model hook

python/ngen_cal/src/ngen/cal/calibration_cathment.py, python/ngen_cal/tests/conftest.py, python/ngen_cal/tests/test_calibration_catchment.py
fixes #166
See #166 for an explanation.
=> fix(test): `test_output`'s monkeypatching of `pd.read_csv`

python/ngen_conf/src/ngen/config/init_config/topmodel.py, python/ngen_conf/tests/conftest.py, python/ngen_conf/tests/data/init_config_data/params.dat, python/ngen_conf/tests/data/init_config_data/subcat.dat, python/ngen_conf/tests/data/init_config_data/topmodel.run, python/ngen_conf/tests/test_init_config_models.py
Initial structures for parsing [`topmodel`](https://github.com/noaa-owp/topmodel) configuration files. Still a few things to sort so it is more compliant with `ngen.init_config`, but this is a good start.
=> feat: add `topmodel` `init_config` models

python/ngen_conf/src/ngen/config/init_config/topmodel.py, python/ngen_conf/src/ngen/config/path_pair/_abc_mixins.py, python/ngen_conf/src/ngen/config/path_pair/path_pair.py, python/ngen_conf/tests/test_init_config_models.py, python/ngen_conf/tests/test_path_pair.py
- `path_pair` type hint fn. Use this instead of `PathPair` (see Feature Details section in #183)
- `Topmodel` `subcat` and `param` fields can now be initialized with `TopModelSubcat` and `TopModelParams` instances respectively.
- Fix `PathPair` & `PathPairCollection` model validation
- Use `path_pair` type hint function in `Topmodel` `init_config` model
- `AbstractPathPairMixin.read` return type hint correct to `bool`. Already returned `bool`, type hint was missing.
`path_pair` type hint function:
In nearly all cases, this should be used as the pydantic model field type if the field is to be a `PathPair[T]`. This will ensure that the `PathPair[T]` instance has the specified `serializer`, `deserializer`, `reader`, and `writer`.
NOTE: if a `PathPair` instance is passed to a model field …
=> Fix `PathPair` & `PathPairCollection` validation;  add `path_pair` type hint fn; use `path_pair` in `Topmodel` `init_config` model

python/ngen_config_gen/src/ngen/config_gen/file_writer.py
closes #179
- write support for `GenericSerializer` subtypes
=> feat: write support for `GenericSerializer`

python/ngen_cal/setup.cfg, python/ngen_conf/src/ngen/config/cfe.py, python/ngen_conf/src/ngen/config/lgar.py, python/ngen_conf/src/ngen/config/topmod.py
- `LgarParams`
- docstrings for `CfeParams`, `TopmodelParams`, and `LgarParams` parameters
- New `CfeParams` and `TopmodelParams` calibratable parameters
- `CfeParams` `bb` and `multiplier` fields dropped. `bb` is now `b`; support for `multiplier` was dropped in https://github.com/NOAA-OWP/cfe/pull/64
- `ngen.cal` on `python` `3.9` pins `fiona<1.10.0` (see notes)
`fiona` `v1.10.0` deprecated  `fiona.path` field (seem to have been removed?) [see](https://github.com/Toblerity/Fiona/releases/tag/1.10.0).
`geopandas` `geojson` reader uses `fiona`.
`geopandas` `v0.14` dropped support for `python<3.9`. So, `ngen.cal` installations are effectively pinned to `geopandas<=0.14`. Transitively, `ngen.cal` needs to pin `fiona<1.10.0` for compatibility. …
=> Update `cfe`, `topmodel`, and `lgar` calibratable parmeters; `ngen.cal` python < 3.9 pin `fiona<1.10.0`

.github/workflows/ngen-cal.yaml, .github/workflows/ngen-conf.yml, .github/workflows/ngen-init-config.yml, python/ngen_conf/src/ngen/config/path_pair/path_pair.py
Fixes #193.
See #193 for detail.
=> fix(py3.12): explicitly call `__init__` to setup `PurePath` instance

CONTRIBUTING.md, doc/RELEASE_MANAGEMENT.md
Making a few more changes to release process documentation to reflect some unique properties of this particular repo.
- Change how release candidate branch is name to reflect time rather than convoluted combination of package versions
- Change order of events in release process, since new version(s) doesn't have to happen before creating the release candidate branch now
- Change steps for the version(s) incrementing to more completely cover the actual process, given the multiple packages that may depend on each other
- Change the step describing applying tags, since the packages and their versions are what matter
- Change discussion of how versions are incremented and such
- Adding a suggestion to use development versions (aligned with Semantic Versioning) to reflect dependency changes …
=> More updates to release process documentation

python/ngen_conf/src/ngen/config/init_config/lstm.py
`lstm` `train_cfg_file` `init_config` field now properly serializes as `str`.
- `lstm` `train_cfg_file` `init_config` field now properly serializes as `str`.
=> fix: `lstm` `pathlib.Path` field serialization
